config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  root 'reports#index'

  get 'uploads', to: 'uploads#index'
  post 'uploads', to: 'uploads#create'

  resources :reports, only: %i[index show destroy] do
    member do
      get 'xml_download'
      get 'danfe_download'
      get 'xlsx_download'
    end
  end

  patch 'change_locale', to: 'application#change_locale'

  get 'up' => 'rails/health#show', as: :rails_health_check
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @query = Nfe.where(user: current_user).joins(:issuer, :recipient).ransack(params[:q])

    @nfes = if params[:cnpj].present? || params[:x_nome].present? || params[:x_mun].present?
              apply_filters(@query.result, params)
            else
              @query.result
            end

    @pagy, @nfes = pagy(@nfes)

    @cnpjs = (Issuer.distinct.pluck(:cnpj) + Recipient.distinct.pluck(:cnpj)).uniq
    @x_nomes = (Issuer.distinct.pluck(:x_nome) + Recipient.distinct.pluck(:x_nome)).uniq
    @x_muns = (Issuer.distinct.pluck(:x_mun) + Recipient.distinct.pluck(:x_mun)).uniq
  end

  def show
    @nfe = Nfe.find(params[:id])

    authorize @nfe, policy_class: ReportPolicy

    @issuer = @nfe.issuer
    @recipient = @nfe.recipient
  end

  def destroy
    nfe = Nfe.find(params[:id])

    authorize nfe, policy_class: ReportPolicy

    nfe.destroy
  end

  def xml_download
    nfe = Nfe.find(params[:id])

    authorize nfe, policy_class: ReportPolicy

    send_data(
      nfe.xml.download,
      filename: "NFe_#{nfe.num_nf}_#{nfe.created_at.to_s.gsub(' UTC', '')}.xml",
      type: nfe.xml.content_type
    )
  rescue StandardError => e
    redirect_to report_path(nfe), alert: I18n.t('notices.alert.file_not_found')
  end

  def danfe_download
    nfe = Nfe.find(params[:id])

    authorize nfe, policy_class: ReportPolicy

    pdf = RubyDanfe.generatePDF(nfe.xml.download).render

    send_data(
      pdf,
      filename: "DANFE_#{nfe.num_nf}_#{nfe.created_at.to_s.gsub(' UTC', '')}.pdf",
      type: 'application/pdf'
    )
  rescue StandardError => e
    redirect_to report_path(nfe), alert: I18n.t('notices.alert.file_not_found')
  end

  def xlsx_download
    nfe = Nfe.find(params[:id])

    authorize nfe, policy_class: ReportPolicy

    xlsx = XlsxGeneratorService.new(nfe).call

    send_data(
      xlsx,
      filename: "NFe_#{nfe.num_nf}_#{nfe.created_at.to_s.gsub(' UTC', '')}.xlsx",
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
  rescue StandardError => e
    redirect_to report_path(nfe), alert: I18n.t('notices.alert.file_not_found')
  end

  private

  def apply_filters(query, params)
    conditions = []
    values = {}

    if params[:cnpj].present?
      conditions << '(issuers.cnpj = :cnpj OR recipients.cnpj = :cnpj)'
      values[:cnpj] = params[:cnpj]
    end

    if params[:x_nome].present?
      conditions << '(issuers.x_nome = :x_nome OR recipients.x_nome = :x_nome)'
      values[:x_nome] = params[:x_nome]
    end

    if params[:x_mun].present?
      conditions << '(issuers.x_mun = :x_mun OR recipients.x_mun = :x_mun)'
      values[:x_mun] = params[:x_mun]
    end

    query = query.where(conditions.join(' AND '), values) if conditions.any?

    query
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_search_form.erb
<%= search_form_for query, url: url do |f| %>
  <div class="row">
    <div class="col">
      <div class="input-group">
        <%= f.search_field search_fields,
                            class: "form-control",
                            placeholder: t("infos.filter_placeholder") %>
        <%= f.submit t("buttons.search"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/reports/index.html.erb
<div class="card px-4 py-4 w-100">
  <div data-controller="filter">
    <div class="d-flex align-items-center justify-content-between flex-row">
      <h1><%= t('infos.nfe_index_title') %></h1>
      <div>
        <%= link_to uploads_path, class: "btn btn-success ml-2" do %>
          <i class="fas fa-plus"></i> <%= t('buttons.new_nfe') %>
        <% end %>
      </div>
    </div>
    <div class="row pt-2 pb-3 text-center gap-3">
      <%= render 'search_form', url: reports_path, query: @query %>
      <%= form_with url: reports_path, method: :get, local: true, class: "d-flex justify-content-between w-100 gap-4" do %>
        <div class="row w-100">
          <div class="col">
            <select class="form-select" id="cnpj" name="cnpj" data-filter-target="select" data-action="change->filter#updateUrlWithParams">
              <option value=""><%= t('infos.filter.cnpj') %></option>
              <% @cnpjs.each do |cnpj| %>
                <option value="<%= cnpj %>"><%= format_cnpj(cnpj) %></option>
              <% end %>
            </select>
          </div>
          <div class="col">
            <select class="form-select" id="x_nome" name="x_nome" data-filter-target="select" data-action="change->filter#updateUrlWithParams">
              <option value=""><%= t('infos.filter.x_nome') %></option>
              <% @x_nomes.each do |x_nome| %>
                <option value="<%= x_nome %>"><%= x_nome %></option>
              <% end %>
            </select>
          </div>
          <div class="col">
            <select class="form-select" id="x_mun" name="x_mun" data-filter-target="select" data-action="change->filter#updateUrlWithParams">
              <option value=""><%= t('infos.filter.x_mun') %></option>
              <% @x_muns.each do |x_mun| %>
                <option value="<%= x_mun %>"><%= x_mun %></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="d-flex gap-3">
          <%= button_tag type: 'submit', class: 'd-flex btn btn-primary align-items-center gap-2', id: 'filter' do %>
            <i class="fas fa-filter"></i> <%= t('buttons.filter') %>
          <% end %>
          <%= button_tag type: 'button', class: 'd-flex btn btn-secondary align-items-center gap-2', id: 'clear-filters', data: { action: 'filter#clearFilters' } do %>
            <i class="fas fa-times"></i> <%= t('buttons.clear') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="table-responsive text-center">
    <% if @nfes.any? %>
      <table class="table table-striped">
        <thead>
          <tr>
            <%# Atributos do nfe %>
            <th class="text-center" scope="col" style="min-width: 200px;"><%= t("activerecord.attributes.nfe.num_nf") %></th>
            <th class="text-center" scope="col" style="min-width: 175px;"><%= t("activerecord.attributes.nfe.v_trib") %></th>
            <th class="text-center" scope="col" style="min-width: 125px;"><%= t("activerecord.attributes.nfe.v_total") %></th>
            <%# Atributos do issuer %>
            <th class="text-center" scope="col"><%= t("activerecord.attributes.issuer.cnpj") %></th>
            <th class="text-center" scope="col" style="min-width: 125px;"><%= t("activerecord.attributes.issuer.x_nome") %></th>
            <th class="text-center" scope="col"><%= t("activerecord.attributes.issuer.x_mun") %></th>
            <%# Atributos do recipient %>
            <th class="text-center" scope="col"><%= t("activerecord.attributes.recipient.cnpj") %></th>
            <th class="text-center" scope="col" style="min-width: 125px;"><%= t("activerecord.attributes.recipient.x_nome") %></th>
            <th class="text-center" scope="col"><%= t("activerecord.attributes.recipient.x_mun") %></th>
          </tr>
        </thead>
        <tbody>
          <% @nfes.each do |nfe| %>
            <tr>
              <%# Atributos do nfe %>
              <td scope="row"><%= link_to nfe.num_nf, report_path(nfe), class: "fw-bold"%></td>
              <td><%= currency_br(nfe.v_trib) %></td>
              <td><%= currency_br(nfe.v_total) %></td>
              <%# Atributos do issuer %>
              <td><%= format_cnpj(nfe.issuer.cnpj) %></td>
              <td><%= nfe.issuer.x_nome %></td>
              <td><%= nfe.issuer.x_mun %></td>
              <%# Atributos do recipient %>
              <td><%= format_cnpj(nfe.recipient.cnpj) %></td>
              <td><%= nfe.recipient.x_nome %></td>
              <td><%= nfe.recipient.x_mun %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%== pagy_bootstrap_nav(@pagy) %>
    <% else %>
      <div class="text-center p-3">
        <h5 class="mb-0 fw-bold">
          <div>
            <%= t('infos.no_results') %>
          </div>
        </h5>
      </div>
    <% end %>
  </div>
</div>